export const mockInstagramProfile = {
  username: 'testuser',
  full_name: 'Test User',
  bio: 'This is a test user bio with #keywords and #hashtags',
  profile_pic_url: 'https://example.com/profile.jpg',
  followers: 1000,
  following: 100,
  posts_count: 50,
  is_verified: false,
  is_business: true,
  is_private: false,
  category: 'Test Category',
  external_url: 'https://example.com',
  engagement_rate: 0.05,
  avg_likes: 50,
  avg_comments: 10,
  posting_frequency: '3 posts/week',
};

export const mockInstagramPosts = [
  {
    id: '1',
    shortcode: '1',
    type: 'image' as const,
    caption: 'This is the first test post with #trending and #topics',
    likes: 100,
    comments: 20,
    timestamp: new Date().toISOString(),
    image_url: 'https://example.com/post1.jpg',
    video_url: null,
    is_sponsored: false,
    hashtags: ['trending', 'topics'],
  },
  {
    id: '2',
    shortcode: '2',
    type: 'image' as const,
    caption: 'This is the second test post with #awesome and #content',
    likes: 200,
    comments: 30,
    timestamp: new Date().toISOString(),
    image_url: 'https://example.com/post2.jpg',
    video_url: null,
    is_sponsored: false,
    hashtags: ['awesome', 'content'],
  },
];
